services:
  - type: web
    name: class-chat-server
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ACCESS_PASSWORD
        value: ">:3"
